### ISSUE TITLE
How to edit the autowalk script to make it compatible with new version of GVR SDK for Unity v1.110.0

### ISSUE THREAD

**Issue by Nish160** [JuppOtto/Autowalk-for-Google-VR-SDK-with-Unity#2]
On attaching the autowalk script to parent (GameObject)containing mainCamera, unity shows the following error:
Assets/Autowalk.cs(68,69): error CS0103: The name `GvrViewer' does not exist in the current context

I would like to know what all changes are to be made in the script to make it compatible with new GVR SDK.

**Comment by JuniorNayal** [comment]
have you found the solution for this?

**Comment by JuppOtto** [comment]
This message means that the class *GvrViewer *do not exist anymore. This is
due to an update of the SDK.
Just delete the parts with the GvrViewer class. So you can use at least the
"walk when look down function".
I will find another solution when I have time. :)

best regards
Jupp

Am 15.12.2017 19:54 schrieb "Nish160" <notifications@github.com>:

**Comment by JuppOtto** [comment]
Fixed the Problem.

**Comment by JuniorNayal** [comment]
Yess i fixed that problem thankyou sir.
